---
title: "Age-adjusted COVID-19 Severity and Outcomes\nAdaptt Tool Example"
author: "Shaun Truelove"
date: "20 August 2020"
output:
  html_document:
    df_print: paged
    fig_caption: true
    theme: lumen
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    pandoc_args: ["--wrap=none", "--top-level-division=chapter"]
  editor_options: 
    chunk_output_type: console
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(root = here::here())
#knitr::opts_chunk$set(root = "..")
#knitr::opts_chunk$set(dev="CairoPNG")
knitr::opts_chunk$set(dev.args = list(png = list(type = "cairo")))

library(tidyverse)
library(covidSeverity)
#devtools::install_github("HopkinsIDD/globaltoolboxlite", force=TRUE)
library(globaltoolboxlite)
library(foreach)
library(doParallel)
library(gridExtra)
library(sf)


# Functions

filter_var <- function(p_var="p_death_inf", countries_=c("ZMB", "COD","KEN"), data = geoid_params){
  data %>% filter(grepl(paste(countries_, collapse = "|"), geoid)) %>% pull(p_var)
}

source("../R/plotting_functions.R")
source("../R/global_functions.R")

```


Load the data
- this was previously generated using *run_global_severity_est.Rmd*       


```{r}
getwd()

geoid_params <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_geoid_params.csv"))
age_pop_10yr <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_age_pop_10yr.csv"))
geodata <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_geodata.csv"))

table(geodata$region)

# Make locations with 0 population estimates NA
geoid_params <- geoid_params %>% 
  dplyr::left_join(geodata %>% dplyr::select(geoid, pop))

cols_to_na <- which(!(colnames(geoid_params) %in% c("geoid","pop")))
which_na <- which(geoid_params$pop==0)
geoid_params[which_na, cols_to_na] <- NA


# add some vars to geoid_params
geoid_params <- geoid_params %>% 
  dplyr::mutate(p_asymp_inf = 1 - p_symp_inf,
                p_asymp_mild_inf = p_asymp_inf + p_mild_inf)


mapdat <- merge_severity_gadm_data(
                              geoid_params = geoid_params,
                              geodata = geodata,
                              shp_adm2 = "../raw_data/gadm36_levels_shp/gadm36_combo.shp",
                              shp_adm0 = "../raw_data/gadm36_levels_shp/gadm36_0.shp",
                              shp2_name_var = "GID_2")

```






# Build the maps

```{r}

mapdat_data <- sf::st_set_geometry(mapdat$shp_adm2, NULL)

regions_ <- sort(unique(mapdat_data$region))
subregions_ <- sort(unique(mapdat_data$subregion))

countries_namerica <- c("USA","CAN","MEX", globaltoolboxlite::get_iso(c("Guatemala","Nicaragua","Honduras","Costa Rica","El Salvador","Belize","Panama")))
countries_africa <- sort(unique(mapdat_data %>% filter(region=="Africa") %>% pull(GID_0)))
countries_europe <- sort(unique(mapdat_data %>% filter(region=="Europe") %>% pull(GID_0)))
countries_samerica <- sort(unique(mapdat_data %>% filter(region=="Americas" & !(GID_0 %in% countries_namerica)) %>% pull(GID_0)))

```


# We are only doing a selection of countries for now
## We can subset to just Africa for now




## Save the data subsetted

```{r}

geoid_params_afr <- subset_geoid_params(   .region = "Africa",
                                   .country = NULL,
                                   region_var = "region",
                                   geoid_params,
                                   geodata )

# Add the district names and other details


outcome_probs_afr <- geoid_params_afr %>% dplyr::select(-pop) %>%
  left_join(geodata %>% dplyr::select(geoid, admin2, admin0, country, pop), by="geoid") %>%
  dplyr::select(geoid, admin2, admin0, country, pop, everything())


write_csv(geoid_params_afr, "../raw_data/geoid_params_afr.csv")
write_csv(outcome_probs_afr, "../raw_data/outcome_probs_afr.csv")


# summarize for the plot

summary(geoid_params_afr$p_hosp_inf)
#summary(geoid_params_afr$p_death_inf)


```






## IFR - Africa

```{r}


hist(mapdat$shp_adm2$p_death_inf, breaks=50)

par(mfrow=c(2,1))
hist(filter_var("p_death_inf", countries_africa, mapdat$shp_adm2), breaks=50, main="IFRs - Africa", xlim = c(0,0.025), xlab="IFR")
hist(filter_var("p_death_inf", countries_namerica, mapdat$shp_adm2), breaks=50, main="IFRs - North America", xlim = c(0,0.025), xlab="IFR")
par(mfrow=c(1,1))



p_death_inf_afr <- map_severity_gadm_fast(severity_var = "p_death_inf", 
                  severity_var_label = "Pr(Death | Infection)",
                  .region = "Africa",
                  .country = NULL,
                  merged_data = mapdat,
                  color_pal = "inferno",
                  legend_pos = c(.2,.2),
                  leg_breaks = seq(0,.025,.005),
                  log_trans = FALSE,
                  leg_range = c(0,.025),
                  border_size = c(.25, .01),
                  label_locs = NA) +
                  coord_sf(xlim = c(-20, 53), ylim=c(-35,40), expand=FALSE) +
                  theme(legend.text=element_text(size=rel(0.5))) +
                  guides(colour=guide_legend(override.aes = list(size = .75)))

ggsave("../raw_data/figures/p_death_africa.png", plot=p_death_inf_afr, dpi=600)



p_hosp_inf_afr <- map_severity_gadm_fast(severity_var = "p_hosp_inf", 
                    severity_var_label = "Pr(Hospitalized | Infection)",
                    .region = "Africa",
                    .country = NULL,
                    merged_data = mapdat,
                    color_pal = "inferno",
                    legend_pos = c(.2,.2),
                    leg_breaks = seq(0,.15,.01),
                    log_trans = FALSE,
                    leg_range = c(0,.15),
                    border_size = c(.25, .01),
                    label_locs = NA) +
                  coord_sf(xlim = c(-20, 53), ylim=c(-35,40), expand=FALSE) +
                  theme(legend.text=element_text(size=rel(0.5))) +
                  guides(colour=guide_legend(override.aes = list(size = .75)))

ggsave("../raw_data/figures/p_hosp_africa.png", plot=p_hosp_inf_afr, dpi=600)

 
# p_death_inf_amr <- map_severity_gadm_fast(severity_var = "p_death_inf", 
#                   severity_var_label = "Pr(Death | Infection)",
#                   .region = "Americas",
#                   region_var = "region",
#                   .country = countries_namerica,
#                   color_pal = "inferno",
#                   merged_data = mapdat,
#                   legend_pos = c(.02,.02),
#                   leg_breaks = seq(0,.025,.005),
#                   log_trans = FALSE,
#                   leg_range = c(0,.025),
#                   border_size = c(.25, .01),
#                   label_locs = NA) +
#                   coord_sf(xlim = c(-180, -55), ylim=c(10,75), expand=FALSE) +
#                   theme(legend.text=element_text(size=rel(0.5))) +
#                   guides(colour=guide_legend(override.aes = list(size = .75)))
# 
# ggsave("raw_data/figures/p_death_NAmerica.png", plot=p_death_inf_amr, dpi=600)
# 
# 
# p_comb <- gridExtra::grid.arrange(p_death_inf_amr +        
#                                     theme(legend.position = c(.4,.2)) +
#                                     guides(colour=guide_legend(override.aes = list(size = .05))),
#                                   p_death_inf_afr +
#                                     theme(legend.position = "none"), 
#                                   ncol=2, nrow=1, widths=c(1.3,1))
# 
# ggsave("raw_data/figures/p_death_NAmerica_Africa.png", plot=p_comb, dpi=600, width = 14, height = 8, units = "in")


```


## Save the data subsetted

```{r}

geoid_params_afr <- subset_geoid_params(   .region = "Africa",
                                   .country = NULL,
                                   region_var = "region",
                                   geoid_params,
                                   geodata )

write_csv(geoid_params_afr, "raw_data/geoid_params_afr.csv")

```








# Proportion not asympt or mild (essentially detectible cases)

```{r}

mapdat$shp_adm2$p_not_asymptmild_inf <- 1 - mapdat$shp_adm2$p_asymp_mild_inf
mapdat_data <- sf::st_set_geometry(mapdat$shp_adm2, NULL)

hist(mapdat$shp_adm2$p_not_asymptmild_inf, breaks=50)
hist(filter_var("p_not_asymptmild_inf", countries_, mapdat$shp_adm2), breaks=50)
hist(filter_var("p_not_asymptmild_inf", "USA", mapdat$shp_adm2), breaks=50)


p_not_asympt_mild <- map_severity_gadm_fast(severity_var = "p_not_asymptmild_inf", 
                  severity_var_label = "Pr(Not Asympt or Mild)",
                  .region = "Africa",
                  .country = NULL,
                  merged_data = mapdat,
                  color_pal = "inferno",
                  legend_pos = c(.2, .2),
                  leg_breaks = seq(0,.2,.05),
                  log_trans = FALSE,
                  leg_range = c(0,.2),
                  border_size = c(.25, .01),
                  label_locs = NA) +
                  coord_sf(xlim = c(-20, 53), ylim=c(-35,40), expand=FALSE) +
                  theme(legend.text=element_text(size=rel(0.5))) +
                  guides(colour=guide_legend(override.aes = list(size = .75)))


#plot(p_not_asympt_mild)
#ggsave("raw_data/figures/p_asymptmild_africa.pdf", plot=p_not_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_notasymptmild_africa.png", plot=p_not_asympt_mild, dpi=600)


p_not_asympt_mild_b <- map_severity_gadm_fast(severity_var = "p_not_asymptmild_inf", 
                  severity_var_label = "Pr(Not Asympt or Mild)",
                  .region = "Americas",
                  region_var = "region",
                  .country = c("USA","CAN","MEX", globaltoolboxlite::get_iso(c("Guatemala","Nicaragua","Honduras","Costa Rica","El Salvador","Belize","Panama"))),
                  color_pal = "inferno",
                  merged_data = mapdat,
                  legend_pos = c(.2,.2),
                  leg_breaks = seq(0,.2,.05),
                  log_trans = FALSE,
                  leg_range = c(0,.2),
                  border_size = c(.25, .01),
                  label_locs = NA) +
                  coord_sf(xlim = c(-180, -55), ylim=c(10,75), expand=FALSE) +
                  theme(legend.text=element_text(size=rel(0.5))) +
                  guides(colour=guide_legend(override.aes = list(size = .75)))

#plot(p_not_asympt_mild_b)
#ggsave("raw_data/figures/p_asymptmild_usa.pdf", plot=p_not_asympt_mild_b, dpi=300)
ggsave("raw_data/figures/p_notasymptmild_NAmerica.png", plot=p_not_asympt_mild_b, dpi=600)


p_comb <- gridExtra::grid.arrange(p_not_asympt_mild_b +        
                                    theme(legend.position = c(.4,.2)) +
                                    guides(colour=guide_legend(override.aes = list(size = .05))),
                                  p_not_asympt_mild +
                                    theme(legend.position = "none"), 
                                  ncol=2, nrow=1, widths=c(1.3,1))

ggsave("raw_data/figures/p_notasymptmild_NAmerica_Africa.png", plot=p_comb, dpi=600, width = 14, height = 8, units = "in")

```























```{r}


countries_ <- get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC"))

par(mfrow=c(2,1))
hist(geoid_params$p_death_inf, breaks=50)
hist(filter_var("p_death_inf", countries_), breaks=50)

hist(geoid_params$p_symp_inf, breaks=50)
hist(filter_var("p_symp_inf", countries_), breaks=50)
summary(filter_var("p_symp_inf", countries_))

hist(geoid_params$p_asymp_mild_inf, breaks=50)
hist(filter_var("p_asymp_mild_inf", countries_), breaks=50)
par(mfrow=c(1,1))


p_ifr <- map_severity_gadm(severity_var = "p_death_inf", 
                  severity_var_label = "IFR",
                  .region = "Africa",
                  .country = countries_,
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = shp_adm2,
                  shp_adm0 = shp_adm0,
                  shp2_name_var = "GID_2",
                  legend_pos = c(.9,.1),
                  leg_breaks = c(0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.007, 0.01),
                  log_trans = TRUE,
                  leg_range = c(0,.01),
                  label_locs = NA)
plot(p_ifr)
#ggsave("raw_data/figures/p_ifr_africa.pdf", plot=p_ifr, dpi=600)
ggsave("raw_data/figures/p_ifr_africa.png", plot=p_ifr, dpi=300)

# Faster version using pre-merged data
p_ifr <- map_severity_gadm_fast(severity_var = "p_death_inf", 
                  severity_var_label = "IFR",
                  .region = "Africa",
                  .country = countries_,
                  merged_data = mapdat,
                  legend_pos = c(.9,.1),
                  leg_breaks = c(0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.007, 0.01),
                  log_trans = TRUE,
                  leg_range = c(0,.01),
                  label_locs = NA)

plot(p_ifr)
#ggsave("raw_data/figures/p_ifr_africa.pdf", plot=p_ifr, dpi=600)
ggsave("raw_data/figures/p_ifr_africa.png", plot=p_ifr, dpi=300)




p_sympt <- map_severity_gadm_fast(severity_var = "p_symp_inf", 
                  severity_var_label = "Pr(Sympt)",
                  .region = "Africa",
                  .country = countries_,
                  merged_data = mapdat,
                  legend_pos = c(.8,.8),
                  leg_breaks = seq(.3,.5, .05),
                  log_trans = FALSE,
                  leg_range = c(.345,.45),
                  label_locs = NA)
plot(p_sympt)
#ggsave("raw_data/figures/p_sympt_africa.pdf", plot=p_sympt, dpi=600)
ggsave("raw_data/figures/p_sympt_africa.png", plot=p_sympt, dpi=300)






p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Africa",
                  .country = countries_,
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = shp_adm2,
                  shp_adm0 = shp_adm0,
                  shp2_name_var = "GID_2",
                  legend_pos = c(.9,.15),
                  leg_breaks = seq(.80,1,.05),
                  log_trans = FALSE,
                  leg_range = c(.80,1),
                  label_locs = NA)

plot(p_asympt_mild)
ggsave("raw_data/figures/p_asymptmild_africa.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_africa.png", plot=p_asympt_mild, dpi=600)



p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Americas",
                  .country = "USA",
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = shp_adm2,
                  shp_adm0 = shp_adm0,
                  shp2_name_var = "GID_2",
                  legend_pos = c(.9,.15),
                  leg_breaks = seq(.80,1,.05),
                  log_trans = FALSE,
                  leg_range = c(.80,1),
                  label_locs = NA) +
                  coord_sf(xlim = c(-150, -60), expand=FALSE)

plot(p_asympt_mild)
ggsave("raw_data/figures/p_asymptmild_usa.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_usa.png", plot=p_asympt_mild, dpi=600)

summary(filter_var("p_asymp_mild_inf", countries_))
summary(filter_var("p_asymp_mild_inf", "USA"))


```



```{r}


summary(filter_var("p_not_asymptmild_inf", countries_, mapdat$shp_adm2))
summary(filter_var("p_not_asymptmild_inf", "USA", mapdat$shp_adm2))













# Americas
summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Americas",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_americas.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_americas.png", plot=p_asympt_mild, dpi=600)




# Europe
summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Europe",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_europe.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_europe.png", plot=p_asympt_mild, dpi=600)






```








```{r}

hist(geoid_params$p_death_inf, breaks=50)

p_ifr <- map_severity_gadm(severity_var = "p_death_inf", 
                  severity_var_label = "IFR",
                  .region = "Africa",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.007, 0.01),
                  log_trans = TRUE,
                  leg_range = c(0,.01),
                  label_locs = NA)

dir.create("raw_data/figures",recursive = TRUE)
ggsave("raw_data/figures/p_ifr_africa.pdf", plot=p_ifr, dpi=600)
ggsave("raw_data/figures/p_ifr_africa.png", plot=p_ifr, dpi=600)



summary(geoid_params$p_symp_inf)
hist(geoid_params$p_symp_inf, breaks=100)

p_sympt <- map_severity_gadm(severity_var = "p_symp_inf", 
                  severity_var_label = "Pr(Sympt)",
                  .region = "Africa",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.3,.75),
                  label_locs = NA)

ggsave("raw_data/figures/p_sympt_africa.pdf", plot=p_sympt, dpi=600)
ggsave("raw_data/figures/p_sympt_africa.png", plot=p_sympt, dpi=600)




summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Africa",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_africa.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_africa.png", plot=p_asympt_mild, dpi=600)







# Americas
summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Americas",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_americas.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_americas.png", plot=p_asympt_mild, dpi=600)




# Europe
summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Europe",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_europe.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_europe.png", plot=p_asympt_mild, dpi=600)






```





# Sub Regions    

```{r}

geoid_params <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_geoid_params.csv"))
age_pop_10yr <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_age_pop_10yr.csv"))
geodata <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_geodata.csv"))

# Make locations with 0 population estimates NA
geoid_params <- geoid_params %>% 
  dplyr::left_join(geodata %>% dplyr::select(geoid, pop, region, who_region, subregion))

cols_to_na <- which(!(colnames(geoid_params) %in% c("geoid","pop")))
which_na <- which(geoid_params$pop==0)
geoid_params[which_na, cols_to_na] <- NA

# add some vars to geoid_params
geoid_params <- geoid_params %>% 
  dplyr::mutate(p_asymp_inf = 1 - p_symp_inf,
                p_asymp_mild_inf = p_asymp_inf + p_mild_inf)
geoid_params_plusregions <- geoid_params
geoid_params <- geoid_params %>% dplyr::select(-c(region, subregion, who_region, pop))


table(geodata$region)
table(geodata$subregion)
table(geodata$who_region)
```



```{r}
# Build the map
hist(geoid_params$p_death_inf, breaks=50)

reg_ <- "Northern America"
reg_var <- "subregion"

hist((geoid_params %>% filter(get(reg_var) %in% reg_))$p_death_inf, breaks=50)


p_ifr <- map_severity_gadm(severity_var = "p_death_inf", 
                  severity_var_label = "IFR",
                  .region = reg_,
                  region_var = reg_var,
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.007, 0.01, 0.02, 0.03),
                  log_trans = FALSE,
                  color_pal = "plasma",
                  label_locs = NA)
p_ifr
dir.create("raw_data/figures",recursive = TRUE, showWarnings = FALSE)
ggsave(paste0("raw_data/figures/p_ifr_", reg_, ".pdf"), plot=p_ifr, dpi=600)
ggsave(paste0("raw_data/figures/p_ifr_", reg_, ".png"), plot=p_ifr, dpi=600)

```



```{r}
reg_ <- " Sub-Saharan Africa"
reg_var <- "subregion"

p_ifr <- map_severity_gadm(severity_var = "p_death_inf", 
                  severity_var_label = "IFR",
                  .region = reg_,
                  region_var = reg_var,
                  .country = NULL, #NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.007, 0.01, 0.02, 0.03),
                  log_trans = FALSE,
                  leg_range = c(0,.015),
                  color_pal = "plasma",
                  label_locs = NA)

dir.create("raw_data/figures",recursive = TRUE, showWarnings = FALSE)
ggsave(paste0("raw_data/figures/p_ifr_", reg_, ".pdf"), plot=p_ifr, dpi=600)
ggsave(paste0("raw_data/figures/p_ifr_", reg_, ".png"), plot=p_ifr, dpi=600)




```


# Run global

```{r}


geoid_params <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_geoid_params.csv"))
age_pop_10yr <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_age_pop_10yr.csv"))
geodata <- readr::read_csv(file.path("../raw_data", "global_severity", "GLOBAL_geodata.csv"))

# Make locations with 0 population estimates NA
geoid_params <- geoid_params %>% 
  dplyr::left_join(geodat %>% dplyr::select(geoid, pop))

cols_to_na <- which(!(colnames(geoid_params) %in% c("geoid","pop")))
which_na <- which(geoid_params$pop==0)
geoid_params[which_na, cols_to_na] <- NA

# add some vars to geoid_params
geoid_params <- geoid_params %>% 
  dplyr::mutate(p_asymp_inf = 1 - p_symp_inf,
                p_asymp_mild_inf = p_asymp_inf + p_mild_inf)


table(geodata$region)
table(geodata$subregion)
table(geodata$who_region)





# Build the map
hist(geoid_params$p_death_inf, breaks=50)

p_ifr <- map_severity_gadm(severity_var = "p_death_inf", 
                  severity_var_label = "IFR",
                  .region = "Africa",
                  region_var = "region",
                  .country = "ZMB", #NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, 0.001, 0.002, 0.003, 0.004, 0.005, 0.007, 0.01, 0.02, 0.03),
                  log_trans = TRUE,
                  color_pal = "plasma",
                  label_locs = NA)

dir.create("raw_data/figures",recursive = TRUE)
ggsave("raw_data/figures/p_ifr_africa.pdf", plot=p_ifr, dpi=600)
ggsave("raw_data/figures/p_ifr_africa.png", plot=p_ifr, dpi=600)



summary(geoid_params$p_symp_inf)
hist(geoid_params$p_symp_inf, breaks=100)

p_sympt <- map_severity_gadm(severity_var = "p_symp_inf", 
                  severity_var_label = "Pr(Sympt)",
                  .region = "Africa",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.3,.75),
                  label_locs = NA)

ggsave("raw_data/figures/p_sympt_africa.pdf", plot=p_sympt, dpi=600)
ggsave("raw_data/figures/p_sympt_africa.png", plot=p_sympt, dpi=600)




summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Africa",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_africa.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_africa.png", plot=p_asympt_mild, dpi=600)







# Americas
summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Americas",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_americas.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_americas.png", plot=p_asympt_mild, dpi=600)




# Europe
summary(geoid_params$p_asymp_mild_inf)
hist(geoid_params$p_asymp_mild_inf, breaks=100)
#tmp <- as.data.frame(table(geoid_params$p_asymp_mild_inf))

p_asympt_mild <- map_severity_gadm(severity_var = "p_asymp_mild_inf", 
                  severity_var_label = "Pr(Asympt or Mild)",
                  .region = "Europe",
                  .country = NULL, #get_iso(c("Zambia","Tanzania", "Uganda","Rwanda","Kenya", "DRC")),
                  geoid_params = geoid_params,
                  geodata = geodata,
                  shp_adm2 = "raw_data/gadm36_levels_shp/gadm36_2.shp",
                  shp_adm0 = "raw_data/gadm36_levels_shp/gadm36_0.shp",
                  shp2_name_var = "GID_2",
                  legend_pos = c(.8,.8),
                  leg_breaks = c(0, .05,.10,.2,.3,.35,.4,.45,.5,.55,.6,.8,1),
                  log_trans = FALSE,
                  leg_range = c(.7,1),
                  label_locs = NA)

ggsave("raw_data/figures/p_asymptmild_europe.pdf", plot=p_asympt_mild, dpi=600)
ggsave("raw_data/figures/p_asymptmild_europe.png", plot=p_asympt_mild, dpi=600)






```

